services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OTEL_SERVICE_NAME=spring-otel-observability-lab
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=prometheus
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_EXPORTER_PROMETHEUS_PORT=9464  
    depends_on:
      - tempo
      - prometheus
      - grafana

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    volumes:
      - ./tempo:/etc/tempo
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.gmail.com:587
      - GF_SMTP_USER=domenico.cassin26@ethereal.email
      - GF_SMTP_PASSWORD=CvhDSUbvXDH9Xa7tZG
      - GF_SMTP_FROM_ADDRESS=domenico.cassin26@ethereal.email
      - GF_SMTP_ALLOW_QUIT=true
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana  # ← FIXED: grafana-data
    depends_on:
      - prometheus
      - tempo
      - loki

  loki:
    image: grafana/loki:2.9.3
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml 

  promtail:
    image: grafana/promtail:2.9.3
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro  # ← ADD THIS
      - ./promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

volumes:
  grafana-data: {}  # ← FIXED: grafana-data