{
 "title": "OpenTelemetry Observability Lab",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Application Logs ",
   "type": "logs",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{app=\"spring-otel-observability-lab\"}"
    }
   ]
  },
  {
   "title": "Distributed Tracing",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "filters": [
      { "id": "604bfb91", "operator": "=", "scope": "span" },
      {
       "id": "service-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "spring-otel-observability-lab" ],
       "valueType": "string"
      },
      {
       "id": "span-name",
       "isCustomValue": false,
       "operator": "=",
       "scope": "span",
       "tag": "name",
       "value": [
        "GET /api/orders",
        "GET /api/payments"
       ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{resource.service.name=\"spring-otel-observability-lab\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": " Success Rate SLO",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{status!=\"5xx\", uri!~\"/actuator.*\"}[5m])\n/\nrate(http_server_requests_seconds_count{uri!~\"/actuator.*\"}[5m])\n* 100",
     "legendFormat": "{{Success}}"
    }
   ]
  },
  {
   "title": "HTTP Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri!~\"/actuator.*\"}[2m])",
     "legendFormat": "{{method}} {{uri}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_sum{uri!~\"/actuator.*\"}[2m]) / rate(http_server_requests_seconds_count{uri!~\"/actuator.*\"}[2m])",
     "legendFormat": "{{method}} {{uri}}"
    },
    {
     "expr": "rate(http_server_requests_seconds_count{status=~\"4..|5..\"}[2m])",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "P95 Latency SLO",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(http_server_requests_seconds_bucket{uri!~\"/actuator.*\"}[5m])) by (le)\n)",
     "legendFormat": "{{Success}}"
    }
   ]
  }
 ]
}